name: Plugin Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Plugin Test
    steps:
      - uses: actions/checkout@v4
      - name: Install subversion
        run: sudo apt-get update && sudo apt-get install -y subversion
      - name: Download and test a plugin
        run: |
          svn co https://plugins.svn.wordpress.org/progress-bar/trunk ./progress-bar
      - uses: ./
        continue-on-error: true
        with:
          type: plugin
          path: ./progress-bar